import subprocess
import tempfile
import click
import git
from .config_command import get_config
from .ai_client import AIClient
import os

system_instruction = """你将作为文本生成器工作，你不会说话，你将以纯文本形式输出你的响应，不包含 Markdown 语法中的代码块（即由 ``` 符号包围的文本内容）。

此外，你的响应不得包含任何形式的代码标记，如：

不使用 ``` 符号包围文本（即 Markdown 代码块）。
不使用 ` 符号（反引号）包围单行代码（即行内代码）。
不使用 HTML 或其他标记语言的 < pre > , < code > 等标签包围文本。
你的输出必须是纯文本，不包含任何代码格式化元素。"""

commit_message_prompt = """你将作为提交消息生成器工作，你将输出消息而不包含代码块，且**你不会说话**。  

请分析已暂存的 diff：  
```diff  
[insert_diff]  
```  
然后，以 [insert_language] 中撰写符合规范的提交消息，包括一个不超过 50 个字符的标题，以及一份每行不超过 70 个字符的详细更改列表。  
请使用适当的类型（例如 'feat:'、'fix:'、'docs:'、'style:'、'refactor:'、'test:'、'chore:' 等）。  

以下是提交消息的格式要求：  

```txt  
<类型>[可选范围]: <标题>  

新增（如适用）：  
- [列出新增的功能。]  
- [包括新的模块、UI 增强等。]  

更改（如适用）：  
- [描述对现有功能的更改。]  
- [注明改进、重构或行为变更。]  

弃用（如适用）：  
- [记录仍然可用但不建议使用、未来版本将移除的功能。]  

移除（如适用）：  
- [列出此次版本中已移除的功能或组件。]  

修复（如适用）：  
- [突出修复的错误或问题。]  
- [如果适用，包含相关的工单或错误报告 ID。]  

安全（如适用）：  
- [提及任何安全改进或已修复的安全漏洞。]  
```  
"""


@click.command()
@click.option('--lang', '-l', default=None, help='Target language for the generated message.')
@click.option('--model', '-m', default=None, help='The model to use for generating the commit message.')
@click.option('--run-dry', '-d', is_flag=True, help='Run the command to print the commit message without actually committing.')
def commit(lang, model, run_dry):
    config = get_config()

    # If arguments are not provided via command line, try to get them from the config file
    lang = lang or config.get('lang', '中文')
    model = model or config.get('default_model')

    if not model:
        raise ValueError(
            "No default model specified in configuration. Please run git-gpt set-default to set default model or run git-gpt config to add model configuration.")

    repo = git.Repo(os.getcwd())
    # add all changes to staged
    repo.git.add('--all')
    # Get textual representation of staged diffs
    diff = repo.git.diff('--staged')

    ai_client = AIClient(config)

    try:
        click.echo(f"Generating commit message with {model} in {lang}...")

        prompt = commit_message_prompt.replace(
            '[insert_diff]', diff).replace('[insert_language]', lang)

        messages = [
            {"role": "system", "content": system_instruction},
            {"role": "user", "content": prompt}
        ]

        response = ai_client.request(messages=messages, model_alias=model)
        commit_message = response

        if run_dry:
            click.echo(
                f"Commit message generated successfully:\n\n{commit_message}")
            return

        # Create a temporary file to hold the commit message
        with tempfile.NamedTemporaryFile(mode='w+', delete=False) as temp_file:
            temp_file.write(f"# Generated by git-gpt\n\n{commit_message}")
            temp_file_name = temp_file.name

        # Use git to open the commit message editing dialog
        try:
            subprocess.run(['git', 'commit', '-e', '-F',
                           temp_file_name], check=True)
            click.echo("Commit created successfully.")
            click.echo(
                "Please run `git commit --amend` to edit the commit message if needed.")
        except subprocess.CalledProcessError:
            click.echo("Failed to create commit. Aborting.")
        finally:
            # Clean up the temporary file
            os.remove(temp_file_name)

    except ValueError as e:
        click.echo(f"Error: {str(e)}")
        click.echo(
            "Please make sure you have set the API key using `git-gpt config --api-key <API_KEY>`")
    except Exception as e:
        click.echo(f"Error generating commit message: {str(e)}")
        click.echo(
            "Please check the ai_client.py file for more details on the error.")
